name: DevOps Course Basic App CI
on : [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses : actions/checkout@v3
    - name : Install dependencies
      run : |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      
    
    